### ISSUE TITLE
We need to generate a list of all of the things people need to do prior to arriving at the hackathon

### ISSUE THREAD

**Issue by mnky9800n** [4DModeller/4DM_Hackathon#3]
Things to do before showing up:

* install R
* install RStudio
* Install INLA, inlabru, fdmr
* join 4dm slack
* make sure they have access to eduroam

please add more here. 

once we feel comfortable we can draft an email and send it out to the participants.

**Comment by KateHeerema** [comment]
Maybe re-iterate they need a GitHub profile & a Terminal? Already emailed before, but I guess it can't hurt to rinse and repeat?

**Comment by mnky9800n** [comment]
@KateHeerema can you send an email and also add the following to the hackathon website:

* people should install R and Rstudio on tehir laptops : https://posit.co/download/rstudio-desktop/
* people should install INLA : https://www.r-inla.org/download-install
* people should install inlabru : https://inlabru-org.github.io/inlabru/index.html
* invite link for slack channel : https://join.slack.com/t/4dmodeller/shared_invite/zt-24fd2cn8i-HZ6NvVy1zSbukC5ZsmfOLg
* reminder for eduroam
* github profile

maybe also creating a slack channel for getting-started could be useful?
